### ISSUE TITLE
texture.rs: .ok().unwrap()

### ISSUE THREAD

**Issue by toqueteos** [PistonDevelopers/gfx_texture#20]
File `src/texture.rs` contains certain instances of `.ok().unwrap()`.

These are a temporal fix for `gfx-rs` not implementing `fmt::Display` on certain types, causing `Result` trait not to be implemented for those types.

A regular `whatever.unwrap()` should do the trick whenever this is fixed.

**Comment by bvssvni** [comment]
Alternative is to use `.expect("Error message")`

**Comment by Potpourri** [comment]
Fixed in #44

**Comment by kvark** [comment]
I'd like to get rid of all `ok.unwrap()` as well. If you encounter a type that is missing `Display`/`Debug`, please let us know.
