### ISSUE TITLE
Implement `ImageSize` on `gfx::TextureHandle`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_texture#25]
See https://github.com/PistonDevelopers/gfx_texture/issues/24

It might be possible to hack around this by:

1. Add a `Size` property to this crate, use piston-quack to implement it for `gfx::TextureHandle`
2. Add an auto impl with a where clause for `ImageSize` using the `Size` property.

If this works, then the compiles should allow 1) because the tuple `(Size, gfx::TextureHandle)` is owned by this crate, and 2) because where clauses can be used as refinements of impls.

**Comment by bvssvni** [comment]
It might be this doesn't work because `ImageSize` and `T` is not owned by this crate, and refinements are ignored.

**Comment by bvssvni** [comment]
Confirmed. This does not work.

**Comment by kvark** [comment]
Perhaps, this is for the better. We could return more info from image loading than just a texture handle. For example, a flag saying that the image had alpha in it. Or the number of bits per component.

**Comment by bvssvni** [comment]
@kvark There is one alternative, where Gfx depends on piston-texture and implements `ImageSize`. https://github.com/PistonDevelopers/texture Not sure if that's the right thing, though.
