### ISSUE TITLE
Generate mipmaps by default

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_texture#26]
See https://github.com/PistonDevelopers/gfx_texture/issues/24#issuecomment-74666588

The motivation for doing this by default is that this is common to do.

**Comment by bvssvni** [comment]
For 2D graphics when you don't zoom in/out you don't need mipmaps. That's the only case I can think of were mipmaps creates overhead.

**Comment by kvark** [comment]
I don't think it is relevant any longer since we have the mipmap flag in the settings now?
