### ISSUE TITLE
What is the difference between `from_image` and `from_rgba8`?

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/gfx_texture#30]
Both use `RgbaImage`. In `from_image` by references, in `from_rgba8` by value. In `from_rgba8` call `generate_mipmap`, in `from_image` no. Both methods are needed?

**Comment by bvssvni** [comment]
You're right. I think `from_rgba8` should take by reference.

**Comment by Potpourri** [comment]
I think these methods look the same, they really do different functions?

**Comment by bvssvni** [comment]
`from_rgba8` generates mipmaps. Should be renamed to `from_image_with_mipmap` or something.

**Comment by Potpourri** [comment]
Ok, now everything is clear. Closed.
