### ISSUE TITLE
error: ... field `handle` does not implement `Copy` 

### ISSUE THREAD

**Issue by stjahns** [PistonDevelopers/gfx_texture#38]
Broken on latest nightly and on [Travis](https://travis-ci.org/PistonDevelopers/gfx_texture/builds/52706331). Not sure if it's a compiler bug. As far as I can tell, `gfx::TextureHandle` should definitely be implementing `Copy`.

**Comment by kvark** [comment]
see https://github.com/gfx-rs/gfx-rs/pull/633
> handles are no longer copyable
