### ISSUE TITLE
Nightly build fails

### ISSUE THREAD

**Issue by Vinatorul** [PistonDevelopers/gfx_texture#67]
Something strange is happening with build on nightly rustc

**Comment by mitchmindtree** [comment]
Indeed, seems to still be hitting an ICE on nightly.

The line where travis fails to build gfx_texture when compiling conrod is [here](https://travis-ci.org/PistonDevelopers/conrod/jobs/78028473#L650).

**Comment by dobrite** [comment]
Should be fixed with Sep 6th's nightly: rustc 1.4.0-nightly (f84d53ca0 2015-09-06) ! :beers:

**Comment by mitchmindtree** [comment]
Cheers @dobrite, looks like both gfx_texture and conrod are building fine now :+1:
