### ISSUE TITLE
How to define types properly?

### ISSUE THREAD

**Issue by xaviershay** [PistonDevelopers/gfx_texture#68]
I am trying to make a wrapper class around textures:

```
impl<R> TextureFactory<R> where R: gfx::Resources
```

I can't figure out how to load textures though:

```
src/main.rs:49:39: 53:23 error: mismatched types:
 expected `gfx_texture::Texture<R>`,
    found `gfx_texture::Texture<gfx_device_gl::Resources>`
(expected type parameter,
    found enum `gfx_device_gl::Resources`) [E0308]
src/main.rs:49             let texture: Texture<R> = gfx_texture::Texture::from_path(
src/main.rs:50                 &mut *window.factory.borrow_mut(),
src/main.rs:51                 assets.join("element_red_square.png"),
src/main.rs:52                 Flip::None, &TextureSettings::new()
src/main.rs:53             ).unwrap();
```

(This is a minimal example - I can't auto-infer the type because I need to store it in a `struct`)

But `gfx_device_gl::Resources` is the device specific implementation, right? AFAICT [it implements `gfx::Resources`](http://www.piston.rs/docs/piston_window/gfx/device/trait.Resources.html).

_I only just started with rust so apologies for what I presume is a noob question..._

**Comment by xaviershay** [comment]
Moved to stackoverflow, that's a better spot I think.

http://stackoverflow.com/questions/32551177/using-rust-traits-with-generics

**Comment by kvark** [comment]
Nice to see you got an answer.
