### ISSUE TITLE
Add `#[derive(Clone, Debug, PartialEq)]` to `Texture`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_texture#76]
Depends on https://github.com/gfx-rs/gfx/issues/857

**Comment by BedfordWest** [comment]
The comment above references this issue having a dependency on [gfx-rs/gfx#857](https://github.com/gfx-rs/gfx/issues/857), which is now closed. Can the derived traits now be restored?

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/gfx_texture/pull/98
